/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
package parser;

public interface EG2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQSTATEMENT = 4;
  public int JJTDECLARESTATEMENT = 5;
  public int JJTASSIGNSTATEMENT = 6;
  public int JJTCONSTATEMENT = 7;
  public int JJTWHILESTATEMENT = 8;
  public int JJTFORSTATEMENT = 9;
  public int JJTDOWHILESTATEMENT = 10;
  public int JJTSWITCHCASESTATEMENT = 11;
  public int JJTLOGICAL = 12;
  public int JJTCONDITION = 13;
  public int JJTEXPRESSION = 14;
  public int JJTADDITIVEEXPRESSION = 15;
  public int JJTMULTIPLICATIVEEXPRESSION = 16;
  public int JJTUNARYEXPRESSION = 17;
  public int JJTRELATION = 18;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "StatementBlock",
    "Statement",
    "SeqStatement",
    "DeclareStatement",
    "AssignStatement",
    "ConStatement",
    "WhileStatement",
    "ForStatement",
    "DoWhileStatement",
    "SwitchCaseStatement",
    "Logical",
    "Condition",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Relation",
  };
}
/* JavaCC - OriginalChecksum=534fa3aa7049c472d7c1d0b19d7cab6a (do not edit this line) */
